openapi: 3.0.0
info:
  title: Company Management API
  version: 1.0.0
  description: API documentation for managing companies and their profiles.

servers:
  - url: /api

tags:
  - name: Company
    description: Endpoints related to company management

paths:
  /company/register:
    post:
      summary: Register a new company with manager
      tags: [Company]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - companyName
                - companyEmail
                - proofDocument
                - companyContact
                - district
                - province
                - sector
                - fullName
                - email
                - password
              properties:
                companyName:
                  type: string
                  example: "Tech Solutions Ltd"
                companyEmail:
                  type: string
                  format: email
                  example: "info@techsolutions.com"
                proofDocument:
                  type: string
                  format: binary
                  description: "Company proof document file upload"
                companyContact:
                  type: string
                  example: "+250788123456"
                district:
                  type: string
                  example: "Gasabo"
                province:
                  type: string
                  example: "Kigali"
                sector:
                  type: string
                  example: "Technology"
                fullName:
                  type: string
                  example: "John Doe"
                email:
                  type: string
                  format: email
                  example: "john.doe@techsolutions.com"
                password:
                  type: string
                  example: "SecurePassword123"
                phoneNumber:
                  type: string
                  example: "0788888888"
      responses:
        "201":
          description: Company and manager created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompanyResponse"

  /company/allCompanies:
    get:
      summary: Get all companies (admin only)
      tags: [Company]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: All companies fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  status:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Company"

  /company/profile:
    patch:
      summary: Update the logged-in company profile (manager only)
      tags: [Company]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                companyLogo:
                  type: string
                  format: binary
                  description: "Company logo image"
                companyName:
                  type: string
                companyEmail:
                  type: string
                companyContact:
                  type: string
                province:
                  type: string
                district:
                  type: string
                sector:
                  type: string
      responses:
        "200":
          description: Company profile updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompanyResponse"

  /company/{companyId}:
    get:
      summary: Get company by ID (admin only)
      tags: [Company]
      security:
        - bearerAuth: []
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Company retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompanyResponse"

    put:
      summary: Update a company by ID (admin only)
      tags: [Company]
      security:
        - bearerAuth: []
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                companyName:
                  type: string
                companyEmail:
                  type: string
                proofDocument:
                  type: string
                  format: binary
                  description: "Updated proof document"
                companyContact:
                  type: string
                province:
                  type: string
                district:
                  type: string
                sector:
                  type: string
      responses:
        "200":
          description: Company updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompanyResponse"

    delete:
      summary: Delete a company by ID (admin only)
      tags: [Company]
      security:
        - bearerAuth: []
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Company deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"

  /company/block/{companyId}:
    patch:
      summary: Block or unblock a company (admin only)
      tags: [Company]
      security:
        - bearerAuth: []
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                state:
                  type: string
                  enum: [active, blocked, trial]
                comment:
                  type: string
      responses:
        "200":
          description: Company state updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompanyResponse"

  /company/approveReject/{companyId}:
    patch:
      summary: Approve or reject a company (admin only)
      tags: [Company]
      security:
        - bearerAuth: []
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  enum: [approved, rejected]
                comment:
                  type: string
      responses:
        "200":
          description: Company approval status updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompanyResponse"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Company:
      type: object
      properties:
        id:
          type: string
          format: uuid
        companyName:
          type: string
        companyEmail:
          type: string
        proofDocument:
          type: string
        companyLogo:
          type: string
          nullable: true
        companyContact:
          type: string
        status:
          type: string
          enum: [pending, approved, rejected]
        state:
          type: string
          enum: [active, blocked, trial]
          nullable: true
        province:
          type: string
        district:
          type: string
        sector:
          type: string
        approveComment:
          type: string
          nullable: true
        blockUnblockComment:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        deletedAt:
          type: string
          format: date-time
          nullable: true

    CompanyResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Company fetched successfully"
        status:
          type: integer
          example: 200
        data:
          $ref: "#/components/schemas/Company"

    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        status:
          type: integer
        data:
          type: "null"

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        status:
          type: integer
        data:
          type: "null"
