openapi: 3.0.3
info:
  title: Managers Mission Actions API
  version: 1.0.0
paths:
  /actions/create:
    post:
      security:
        - bearerAuth: []
      tags:
        - Managers Mission Actions
      summary: Create a new mission action
      description: Create a new action (approval, rejection, update, cancellation, or complete) for a mission
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMissionAction'
      responses:
        '201':
          description: Mission action created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MissionActionResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /actions:
    get:
      security:
        - bearerAuth: []
      tags:
        - Managers Mission Actions
      summary: Get all Managers Mission Actions
      description: Retrieve a list of all Managers Mission Actions in the system
      responses:
        '200':
          description: List of Managers Mission Actions retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MissionActionResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /actions/{missionId}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Managers Mission Actions
      summary: Get actions by mission ID
      description: Retrieve all actions for a specific mission
      parameters:
        - name: missionId
          in: path
          required: true
          description: UUID of the mission
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Managers Mission Actions retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MissionActionResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /actions/action/{actionId}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Managers Mission Actions
      summary: Get action by ID
      description: Retrieve a specific mission action by its ID
      parameters:
        - name: actionId
          in: path
          required: true
          description: UUID of the action
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Mission action retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MissionActionResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    patch:
      security:
        - bearerAuth: []
      tags:
        - Managers Mission Actions
      summary: Finance manager updates a mission action
      description: Update an existing mission action (finance manager only)
      parameters:
        - name: actionId
          in: path
          required: true
          description: UUID of the action to update
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMissionAction'
      responses:
        '200':
          description: Mission action updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MissionActionResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      security:
        - bearerAuth: []
      tags:
        - Managers Mission Actions
      summary: Delete a mission action
      description: Delete a specific mission action by its ID
      parameters:
        - name: actionId
          in: path
          required: true
          description: UUID of the action to delete
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Mission action deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CreateMissionAction:
      type: object
      required:
        - missionId
        - action
      properties:
        missionId:
          type: string
          format: uuid
          description: ID of the mission
        action:
          type: string
          enum: [Approve, Reject, Update, Cancel, Complete]
          description: Type of action being performed
        comment:
          type: string
          description: Optional comment for the action

    UpdateMissionAction:
      type: object
      properties:
        action:
          type: string
          enum: [Approve, Reject, Update, Cancel, Complete]
        accomodationAmount:
          type: number
          description: Optional accommodation amount
        transportAmount:
          type: number
          description: Optional transport amount
        dailyAllowanceAmount:
          type: number
          description: Optional daily allowance amount
        totalAmount:
          type: number
          description: Optional total amount
        comment:
          type: string
          description: Optional comment for the action

    MissionActionResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        actorId:
          type: string
          format: uuid
        action:
          type: string
          enum: [Approve, Reject, Update, Cancel, Complete]
        comment:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        mission:
          $ref: '#/components/schemas/MissionDetails'
        actor:
          $ref: '#/components/schemas/UserDetails'

    MissionDetails:
      type: object
      properties:
        id:
          type: string
          format: uuid
        missionTitle:
          type: string
        location:
          type: string

    UserDetails:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email

  responses:
    NotFound:
      description: The specified resource was not found
    BadRequest:
      description: Bad request - invalid input data
    Unauthorized:
      description: Unauthorized - invalid or missing token / insufficient role
    InternalServerError:
      description: Internal server error
